before:
  hooks:
    - go mod download
builds:
- id: hello
  main: ./cmd/
  binary: hello
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
  goarm: [6, 7]

archives:
- id: hello-archive
  name_template: |-
    hello_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    {{- with .Arm -}}
      {{- if (eq . "6") -}}hf
      {{- else -}}v{{- . -}}
      {{- end -}}
    {{- end -}}
  builds:
    - hello
  format_overrides:
    - goos: windows
      format: zip
#  files:
#    - ./run.sh
#    - ./tools/preflight/*
#    - ./build/preflight.tar.gz
#    - ./build/preflight-sha256.txt
#    - tvm.yaml

checksum:
  name_template: "hello-checksums.txt"
  algorithm: sha256

release:
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # You can add extra pre-existing files to the release.
  # The filename on the release will be the last part of the path (base). If
  # another file with the same name exists, the latest one found will be used.
  # Defaults to empty.
  extra_files:
    - glob: ./run.sh
#    - glob: ./tools/preflight/*
    - glob: ./build/preflight.tar.gz
    - glob: ./build/preflight-sha256.txt
    - glob: tvm.yaml