# CI WorkFlow for kubectl-plugins
name: CI for Plugins Packages
on:
  push:
    paths-ignore:
      - 'plugins/**'
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          fail_on_error: false
          reporter: local
          filter_mode: nofilter

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Run Shell lint
        run: hack/run-shell-lint.sh

      - name: Verify code patterns
        run: hack/verify-code-patterns.sh

  preflight:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Preflight Package
      run: hack/build-preflight-artifacts.sh

      #- name: Run integration tests
      #  run: hack/run-integration-tests.sh

    - name: Ensure Required Utilities Installed
      run: hack/install-required-utilities.sh

    - name: Test Preflight Plugin Locally
      run: |
        hack/generate-test-preflight-plugin-manifest.sh
        hack/test-preflight-plugin-locally.sh

    - uses: actions/upload-artifact@v2
      with:
        name: preflight
        path: |
          build/preflight.tar.gz
          build/preflight-sha256.txt

  log-collector:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build Log-Collector Packages
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --skip-publish --rm-dist

      #- name: Run integration tests
      #  run: hack/run-integration-tests.sh

      - name: Ensure Required Utilities Installed
        run: hack/install-required-utilities.sh

      - name: Test Log-Collector Plugin Locally
        run: |
          hack/generate-test-log-collector-plugin-manifest.sh
          hack/test-log-collector-plugin-locally.sh

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [preflight, log-collector]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: preflight
          path: build

      - name: Display structure of downloaded files
        run: ls -R

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
