name: Kubernetes-sigs/krew CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.14]
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

#      - name: Install gox
#        run: hack/install-gox.sh

      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --no-patch --exit-code

      - name: Verify code patterns
        run: hack/verify-code-patterns.sh

      - name: Run Shell lint
        run: hack/run-lint.sh

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

#      - name: Run unit tests
#        run: go test -short ./...

      - name: Make binaries && verify plugins installation
        run: hack/make-all.sh

      - name: Ensure kubectl & helm installed
        run: hack/ensure-kubectl-and-helm-installed.sh

      - name: Verify installation
        run: hack/verify-installation.sh

#      - name: Run integration tests
#        run: hack/run-integration-tests.sh

      - name: Create a new release
        if: contains(github.ref, 'tags')
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

#      - name: Upload binaries to the new release
#        if: contains(github.ref, 'tags')
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: out/krew.*
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true