# CI WorkFlow for testing Plugin Manifests
name: CI for Plugin Manifests
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'plugins/**'
      - 'hack/test-plugin-manifests.sh'
      - 'hack/install-required-utilities.sh'
      - '.github/workflows/plugins.yml'

jobs:
  validate-plugin-manifests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run yaml lint
      uses: reviewdog/action-yamllint@v1
      with:
        fail_on_error: true
        reporter: local
        filter_mode: nofilter

    - name: Ensure Required Utilities Installed
      run: hack/install-required-utilities.sh

    - name: Validate Updated Plugin Manifests
      run: hack/test-plugin-manifests.sh
