# CI WorkFlow for testing Plugin Manifests
name: Plugin Manifests CI
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'plugins/**'
      - 'hack/validate-plugin-manifests.sh'
      - 'hack/install-required-utilities.sh'
      - '.github/workflows/plugin-manifests.yml'

jobs:
  # validate-plugin-manifests job validates plugin manifests which are under 'plugins' dir
  # (Checks structural schema, version semantics, install & uninstall of plugins using plugin manifests yaml)
  validate-plugin-manifests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run yaml lint
      uses: reviewdog/action-yamllint@v1
      with:
        fail_on_error: true
        reporter: local
        filter_mode: nofilter

    - name: Run Shell lint
      run: hack/run-shell-lint.sh

    - name: Ensure Required Utilities Installed
      run: hack/install-required-utilities.sh

    - name: Validate Updated Plugin Manifests
      run: hack/validate-plugin-manifests.sh
