# CI WorkFlow for build, test and release of Plugin Packages
name: Plugin Packages CI
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'plugins/**'
      - 'hack/validate-plugin-manifests.sh'
      - 'hack/update-plugin-manifests.sh'
      - 'hack/update-preflight-manifest.sh'
      - 'hack/update-log-collector-manifest.sh'
      - '.github/workflows/plugin-manifests.yml'

env:
  GKE_CLUSTER: ci-cluster
  GKE_ZONE: us-east1-c

jobs:
  # pre-build job runs yaml lint, shell lint, golangci-lint and detects file changes to sets job variables which will be used to
  # decide whether to run subsequent jobs(build_test_preflight and build_test_log-collector)
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      preflight: ${{ steps.filter.outputs.preflight }}
      testPreflight: ${{ steps.filter.outputs.testPreflight }}
      logCollector: ${{ steps.filter.outputs.logCollector }}
      testLogCollector: ${{ steps.filter.outputs.testLogCollector }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect File Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            preflight:
              - 'Makefile'
              - 'hack/**'
              - '.krew/tvk-preflight.yaml'
              - 'tools/preflight/**'
              - '.goreleaser.yml'
              - 'tests/preflight/**'
              - 'tests/common/**'
            logCollector:
              - 'Makefile'
              - 'cmd/**'
              - 'hack/**'
              - '.krew/tvk-log-collector.yaml'
              - 'tools/log-collector/**'
              - '.goreleaser.yml'
              - 'tests/log-collector/**'
              - 'tests/common/**'
            testPreflight:
              - 'tools/preflight/**'
              - 'tests/preflight/**'
            testLogCollector:
              - 'cmd/**'
              - 'tools/log-collector/**'
              - 'tests/log-collector/**'
              - 'tests/common/**'

  # build_test_preflight job build preflight packages, runs integration tests and tests packages for plugin creation(install, uninstall)
  # upload preflight packages to github artifacts if tags('/ref/tags') are pushed
  build_test_preflight:
    runs-on: ubuntu-latest
    needs: pre-build
    # for tags('ref/tags/'), 'needs.pre-build.outputs.preflight' will be 'false' so to run 'build_test_preflight' job on tags as well,
    # added condition 'startsWith(github.ref, 'refs/tags/')'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Preflight Package
      run: make build-preflight

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Authenticate and Connect to GKE cluster
      uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Run Preflight Integration Tests
      if: needs.pre-build.outputs.testPreflight == 'true'
      run: |
        GO111MODULE=off go get -u github.com/onsi/ginkgo/ginkgo
        ginkgo -r -keepGoing tests/preflight/

    - name: Ensure Required Utilities Installed
      run: make install-required-utilities

    - name: Test Preflight Plugin Locally
      run: make test-preflight-plugin-locally

    - name: Upload Preflight Plugin Packges to github artifact
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: preflight
        path: |
          build/preflight.tar.gz
          build/preflight-sha256.txt

  # build_test_log-collector job builds log-collector packages, runs integration tests and tests packages for plugin creation(install, uninstall)
  build_test_log-collector:
    runs-on: ubuntu-latest
    needs: pre-build
    # for tags('ref/tags/'), 'needs.pre-build.outputs.logCollector' is 'false' so to run 'build_test_log-collector' job on tags as well,
    # added condition 'startsWith(github.ref, 'refs/tags/')'
    if: (needs.pre-build.outputs.logCollector == 'true') || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build Log-Collector Packages
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --skip-publish --rm-dist

      - name: Setup Pre-requisuites of TVK License Creation
        if: needs.pre-build.outputs.testLogCollector == 'true'
        run: |
          sudo apt-get install libssl-dev swig python3-dev gcc python3-setuptools
          pip3 install M2Crypto==0.35.2
          printf "%s" "$TRILIODATA" > triliodata
        env:
          TRILIODATA: ${{secrets.TRILIODATA}}

      - name: Authenticate and Connect to GKE cluster
        if: needs.pre-build.outputs.testLogCollector == 'true'
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Run Log-collector Integration Tests
        if: needs.pre-build.outputs.testLogCollector == 'true'
        run: hack/run-integration-tests.sh tests/log-collector/
        env:
          job_name: log-collector
          build_id: logcollector-${{ github.run_id }}

      - name: Ensure Required Utilities Installed for Plugin Testing
        run: make install-required-utilities

      - name: Test Log-Collector Plugin Locally
        run: make test-log-collector-plugin-locally

  # pre-release job determines whether to create release or not and sets job variables which will be used to decide
  # what packages(preflight or log-collector or both) should be included in release
  pre-release:
    runs-on: ubuntu-latest
    needs: [build_test_preflight, build_test_log-collector]
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      create_release: ${{ steps.detect_changes.outputs.create_release }}
      release_preflight: ${{ steps.detect_changes.outputs.release_preflight }}
      release_log_collector: ${{ steps.detect_changes.outputs.release_log_collector }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine File Changes for Release
        id: detect_changes
        run: hack/check-git-diff-between-tags.sh

  # release job creates and uploads release on github. Also, decides which package to include in release based on conditional constructs
  release:
    runs-on: ubuntu-latest
    needs: pre-release
    if: needs.pre-release.outputs.create_release == 'true' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Preflight Packages from Artifact
        uses: actions/download-artifact@v2
        if: needs.pre-release.outputs.release_preflight == 'true'
        with:
          name: preflight
          path: build

      - name: Update GoReleaser Config for Release
        run: hack/update-goreleaser-yaml.sh
        env:
          release_preflight: ${{needs.pre-release.outputs.release_preflight}}
          release_log_collector: ${{needs.pre-release.outputs.release_log_collector}}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
