# CI WorkFlow for Plugin Manifests
name: CI for Plugin Manifests
on:
  push:
    paths:
      - 'plugins/**'
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  plugins:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run yaml lint
      uses: reviewdog/action-yamllint@v1
      with:
        fail_on_error: true
        reporter: local
        filter_mode: nofilter

    - name: Ensure Required Utilities Installed
      run: hack/install-required-utilities.sh

    - name: Validate Updated Plugin Manifests
      run: hack/test-plugin-manifests.sh
